'use strict';
/**
 * Skill Gap Analysis. Role requirements are generated by the AI (and cached),
 * the user's levels come from stored assessment results, and every number in
 * the report is computed from those two sources – nothing is hard-coded.
 */
const db = require('../db');
const ai = require('../ai');
const { requireUser } = require('../auth');
const { HttpError, createLimiter } = require('../http');
const { parseJson, notify, str, getAssessedSkills } = require('../context');
const { skillKey, clampPct } = require('../skills');

const limiter = createLimiter({ windowMs: 10 * 60 * 1000, max: 12 });
const IMPORTANCE_WEIGHT = { critical: 3, important: 2, nice_to_have: 1 };
const CACHE_DAYS = 45;

const roleKey = (r) => r.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim();

async function getRoleRequirements(role) {
  const key = roleKey(role);
  const cached = db.get('SELECT * FROM role_requirements WHERE role_key = ?', key);
  if (cached && Date.now() - new Date(cached.created_at).getTime() < CACHE_DAYS * 86400000) {
    return { title: cached.role_title, ...parseJson(cached.requirements_json, {}) };
  }
  const data = await ai.generateJSON({
    system: 'You are a hiring-requirements analyst who knows what employers expect for each role. Output ONLY one JSON object.',
    prompt: `Job role: "${role}"

Define the skills an ENTRY-LEVEL / early-career candidate (0-2 years, fresher to junior) is normally expected to have to be hired for this role, based on typical current job descriptions.

Rules
- If "${role}" is not a real job role, return {"error":"<short reason>"}.
- List 5-8 skills. Use widely recognised names such as "JavaScript", "Python", "HTML", "CSS", "Node.js", "Database", "Front-End Development", "Communication", "Software Testing".
- "required_percent": the proficiency (0-100) an employer expects at hiring level. Be realistic: entry-level expectations are usually 40-80.
- "importance": "critical", "important" or "nice_to_have".
- "why": one short sentence on why the skill matters for the role.

Return JSON: {"role":"<normalised role title>","summary":"<one sentence describing the role>","skills":[{"name":"JavaScript","required_percent":70,"importance":"critical","why":"..."}]}`,
    temperature: 0.3,
    validate: (o) => {
      if (o?.error) throw new HttpError(422, `"${role}" doesn't look like a job role: ${String(o.error).slice(0, 120)}`);
      if (!Array.isArray(o?.skills) || o.skills.length < 3) throw new Error('need at least 3 skills');
      const skills = o.skills.slice(0, 10).map((s) => ({
        name: String(s.name || '').trim().slice(0, 60),
        required_percent: clampPct(s.required_percent),
        importance: IMPORTANCE_WEIGHT[s.importance] ? s.importance : 'important',
        why: String(s.why || '').slice(0, 200),
      })).filter((s) => s.name);
      if (skills.length < 3) throw new Error('need at least 3 valid skills');
      return { role: String(o.role || role).slice(0, 80), summary: String(o.summary || '').slice(0, 300), skills };
    },
  });
  const value = { summary: data.summary, skills: data.skills };
  db.run('INSERT OR REPLACE INTO role_requirements (role_key, role_title, requirements_json, created_at) VALUES (?,?,?,?)',
    key, data.role, JSON.stringify(value), db.now());
  return { title: data.role, ...value };
}

function computeRows(requirements, assessed) {
  const byKey = new Map(assessed.map((s) => [skillKey(s.name), s]));
  return requirements.skills.map((r) => {
    const mine = byKey.get(skillKey(r.name));
    if (!mine) {
      return { skill: r.name, required: r.required_percent, current: null, gap: null, status: 'not_assessed', importance: r.importance, why: r.why };
    }
    const gap = r.required_percent - mine.score;
    return {
      skill: r.name, required: r.required_percent, current: mine.score, gap: Math.max(0, gap),
      status: mine.score >= r.required_percent ? 'strong' : 'improve',
      importance: r.importance, why: r.why, level: mine.level,
    };
  });
}

function readiness(rows) {
  let num = 0; let den = 0; let covered = 0; let total = 0;
  for (const r of rows) {
    const w = IMPORTANCE_WEIGHT[r.importance] || 2;
    total += w;
    if (r.current === null) continue;
    covered += w; den += w;
    num += w * Math.min(r.current / Math.max(1, r.required), 1);
  }
  return { percent: den ? Math.round((num / den) * 100) : null, coverage: total ? Math.round((covered / total) * 100) : 0 };
}

async function buildFocus(role, rows, readinessPct) {
  const todo = rows.filter((r) => r.status !== 'strong');
  const fallback = todo
    .slice().sort((a, b) => (b.gap ?? 100) - (a.gap ?? 100))
    .slice(0, 5).map((r) => ({
      skill: r.skill, priority: r.importance === 'critical' ? 'high' : 'medium',
      why: r.status === 'improve' ? `Your assessed level is ${r.current}% but ${r.required}% is expected.` : 'Not assessed yet – take an assessment to measure it.',
      actions: [], timeframe: '',
    }));
  if (!todo.length) return { summary: `You already meet the requirements for every assessed skill in this role.`, focus: [] };
  try {
    const out = await ai.generateJSON({
      system: 'You are a practical career coach. Output ONLY one JSON object. Base advice strictly on the numbers provided.',
      prompt: `Target role: ${role}. Overall readiness: ${readinessPct === null ? 'unknown' : readinessPct + '%'}.
Skill comparison (JSON): ${JSON.stringify(rows.map((r) => ({ skill: r.skill, required: r.required, current: r.current, status: r.status, importance: r.importance })))}

Write recommendations for the skills whose status is "improve" or "not_assessed" (largest impact first, max 5).
Return JSON: {"summary":"2-3 sentence honest summary of readiness","focus":[{"skill":"<exact skill name from the list>","priority":"high|medium|low","why":"one sentence using the actual numbers","actions":["2-3 concrete practice actions"],"timeframe":"e.g. 2-3 weeks"}]}`,
      temperature: 0.4,
      validate: (o) => {
        if (!Array.isArray(o?.focus)) throw new Error('missing focus array');
        return {
          summary: String(o.summary || '').slice(0, 600),
          focus: o.focus.slice(0, 6).map((f) => ({
            skill: String(f.skill || '').slice(0, 60), priority: ['high', 'medium', 'low'].includes(f.priority) ? f.priority : 'medium',
            why: String(f.why || '').slice(0, 300),
            actions: (Array.isArray(f.actions) ? f.actions : []).slice(0, 4).map((a) => String(a).slice(0, 240)),
            timeframe: String(f.timeframe || '').slice(0, 40),
          })).filter((f) => f.skill),
        };
      },
    });
    return out;
  } catch (e) {
    console.warn('[gap] focus recommendations failed:', e.message);
    return { summary: '', focus: fallback };
  }
}

module.exports = function (router) {
  router.post('/api/gap/analyze', async ({ req, body }) => {
    const u = requireUser(req);
    limiter.check(String(u.id));
    const b = await body();
    const role = str(b.role, { field: 'Target role', min: 2, max: 80, required: true });
    const assessed = getAssessedSkills(u.id);
    if (!assessed.length) throw new HttpError(409, 'Complete an AI Skill Assessment first – the gap analysis compares your assessed skills with the role requirements.');
    ai.ensureConfigured();

    const requirements = await getRoleRequirements(role);
    const rows = computeRows(requirements, assessed);
    const rd = readiness(rows);
    const focusOut = await buildFocus(requirements.title, rows, rd.percent);

    const result = {
      role: requirements.title, roleSummary: requirements.summary,
      readiness_percent: rd.percent, coverage_percent: rd.coverage,
      rows,
      strong: rows.filter((r) => r.status === 'strong').map((r) => r.skill),
      improve: rows.filter((r) => r.status === 'improve').map((r) => r.skill),
      not_assessed: rows.filter((r) => r.status === 'not_assessed').map((r) => r.skill),
      summary: focusOut.summary, focus: focusOut.focus,
    };
    const r = db.run('INSERT INTO gap_analyses (user_id, role_title, result_json, readiness, created_at) VALUES (?,?,?,?,?)',
      u.id, result.role, JSON.stringify(result), rd.percent, db.now());

    const worst = rows.filter((x) => x.status === 'improve').sort((a, b2) => b2.gap - a.gap)[0];
    notify(u.id, 'gap', `Skill gap for ${result.role}: ${rd.percent === null ? 'no assessed skills yet' : rd.percent + '% ready'}`,
      worst ? `Biggest gap: ${worst.skill} (${worst.current}% vs ${worst.required}% required).` : 'No assessed skill is below the requirement.', 'skill-gap');
    return { analysis: { id: Number(r.lastInsertRowid), createdAt: db.now(), ...result } };
  });

  router.get('/api/gap/latest', ({ req }) => {
    const u = requireUser(req);
    const g = db.get('SELECT * FROM gap_analyses WHERE user_id = ? ORDER BY id DESC LIMIT 1', u.id);
    return { analysis: g ? { id: g.id, createdAt: g.created_at, ...parseJson(g.result_json, {}) } : null };
  });

  router.get('/api/gap/history', ({ req }) => {
    const u = requireUser(req);
    return { history: db.all('SELECT id, role_title AS role, readiness, created_at AS createdAt FROM gap_analyses WHERE user_id = ? ORDER BY id DESC LIMIT 20', u.id) };
  });

  router.get('/api/gap/:id', ({ req, params }) => {
    const u = requireUser(req);
    const g = db.get('SELECT * FROM gap_analyses WHERE id = ? AND user_id = ?', Number(params.id), u.id);
    if (!g) throw new HttpError(404, 'Analysis not found.');
    return { analysis: { id: g.id, createdAt: g.created_at, ...parseJson(g.result_json, {}) } };
  });
};
